import React, { useEffect } from "react";
import "./merchantNotificationService.css";
import CopyAllIcon from "@mui/icons-material/CopyAll";

function MerchantNotificationService() {
  useEffect(() => {
    document.getElementById("copyIcon8").onclick = () => {
      navigator.clipboard.writeText(
        "https://{base_url} /transaction/013/status?user=apiuser&password=apiuserpassword&sid=900000&mdorder=eed077dc-cad0-4ed5-8a15-608ffc592173"
      );
      alert("Successfully copied to Clickboard!");
    };
  }, []);

  return (
    <div id="notification" className="merchantNotificationService">
      <h1 className="componentHeading">
        Merchant Notification Service(Call Back)
      </h1>
      <p className="componentParagraph">
        The notification service sends a message in{" "}
        <span className="text-bold">JSON</span> format using a{" "}
        <span className="text-bold">TLS</span> protocol to the merchant
        specified <span className="text-bold">URL</span> of the
        <br /> service with <span className="text-bold">POST</span> method.
        <br />
        <br />
        <span className="text-bold">{"Response parameters:"}</span>
      </p>

      <br />
      <table className="componentTable">
        <thead>
          <tr>
            <td>Name</td>
            <td>Type</td>
            <td>Mandatory</td>
            <td>Description</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>description</td>
            <td>ANS..100</td>
            <td>Yes</td>
            <td>Free form description of the order error.</td>
          </tr>
          <tr>
            <td>amount</td>
            <td>N..12</td>
            <td>Yes</td>
            <td>
              Amount to be debited in the order currency. The amount can be less
              or equal to the preauthorization amount.
            </td>
          </tr>
          <tr>
            <td>fee</td>
            <td>N..9</td>
            <td>Yes</td>
            <td>Fee amount</td>
          </tr>
          <tr>
            <td>orderId</td>
            <td>AN..30</td>
            <td>Yes</td>
            <td>
              Order number generated by EPG after the registration of the order
              (the same as the <span className="text-bold"> mdOrder</span>{" "}
              parameter).
            </td>
          </tr>
          <tr>
            <td>code</td>
            <td>N1..6</td>
            <td>Yes</td>
            <td>Error code or 0 if order paid successfully.</td>
          </tr>
          <tr>
            <td>timestamp</td>
            <td>ANS</td>
            <td>Yes</td>
            <td>Date and time of order payment.</td>
          </tr>
          <tr>
            <td>success</td>
            <td>Boolean</td>
            <td>Yes</td>
            <td></td>
          </tr>
          <tr>
            <td>rrn</td>
            <td>AN..24</td>
            <td>No</td>
            <td>Reference number. It is specified only for paid orders.</td>
          </tr>
          <tr>
            <td>auth</td>
            <td>AN6</td>
            <td>No</td>
            <td>
              Payments network authorization code. The field has a fixed length
              of six characters; it can contain both numbers and letters. It is
              specified only for paid orders.
            </td>
          </tr>
          <tr>
            <td>currency</td>
            <td>N3</td>
            <td>Yes</td>
            <td>Payment currency in the ISO 4217 format.</td>
          </tr>
          <tr>
            <td>pan</td>
            <td>N 12...19</td>
            <td>No</td>
            <td>
              Masked number of the card that has been used for the payment.{" "}
            </td>
          </tr>
          <tr>
            <td>orderNumber</td>
            <td>AN 1..32</td>
            <td>Yes</td>
            <td>
              Number (identifier) of the order in the merchant’s online store
              system. It is unique for every store in the system.
            </td>
          </tr>
          <tr>
            <td>status</td>
            <td>AN..80</td>
            <td>Yes</td>
            <td>Order status</td>
          </tr>
        </tbody>
      </table>

      <p className="componentParagraph">
        <br />
        <span className="text-bold">{"Response example:"}</span>
        <br />
        <br />
        <span className="iframe">
          <span className="text-url">{"{"}</span>
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;"status":"CREATED",
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;"description":"No payment attempted yet.",
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;"amount":"0.00",
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;"fee":"0.00",
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;"orderId":"409082c1-5380-4f07-b5b3-f52ee159041c",
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;"code":"-100",
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;"orderStatus":"0",
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;"timestamp":"2022-11-10 00:45:15",
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;"success":false,
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;"rrn":null,
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;"auth":"-",
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;"currency":"978",
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;"pan":"",
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;"orderNumber":"2022111014514158",
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;"signature":"LFYgBrBrA6v7he1l4jUgnTT2kRgMsqEYzLqEeu9zUZGMptpHmxpqz3GLR6EkkgDt8Hc0cvvH9oi/x53M
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;nAcYGQWfw4eF7AqGbFa0TDATppL8q33xUXsuEJiqWWvK6ox6FRiiNbNvl52VPffPz1TWnZdcGHIZzfRLpPje/9P1wn
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;EsiaZgX1NQsKASEDdCJ3UZ7NruMzfPrpcq8el4kpdkMRAh59ETLVw/kuRpPof+yx12ISQuOiqsXUT5Lx009xVLEoOS
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;nt7CMw3TnA64gezJfhTob91Shykw//8Ypj2+WoiJGaixikF0H0GEfsjRBFojy8OKdxBwWM5ntgX/NWBGRw=="
          <br />
          <span className="text-url">{"}"}</span>
        </span>
        <br />
        <br />
        <span className="text-bold">{"Hash calculation for signature:"}</span>
        <br />
        The hash is calculated from a string consisting of ‘name=value’ pairs
        connected by '&'.
        <br />
        <br />
        <span className="text-bold">Example:</span>
        <br />
        status=CREATED&description=No payment attempted
        yet.&amount=0.00&fee=0.00&orderId=5d696a3b-afb0-4111-b201-ea00bc68c862&code=-100&orderStatus=0&timestamp=2022-11-10
        01:14:20&success=false&rrn&auth=-&currency=978&pan=&orderNumber=2022111021419470
        &nbsp;&nbsp;
        <CopyAllIcon className="copyIcon" id="copyIcon8" fontSize="medium" />
      </p>
    </div>
  );
}

export default MerchantNotificationService;
